// <auto-generated />
namespace Mod6_TP1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Dojo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Dojo));
        
        string IMigrationMetadata.Id
        {
            get { return "202009231251436_Dojo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
